server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://47.105.226.190:3306/socks?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hollyipcc!qaZ

mybatis:
    type-aliases-package: com.cn.nginx.entity
    mapper-locations: classpath:mapper/*.xml

system:
    switch: normal
    url: http://xx
    secret: 123456
